### ISSUE TITLE
Use the Visual Studio Code GUI within docker on Windows

### ISSUE THREAD

**Issue by PrasadBabarendaGamage** [OpenCMISS-Examples/basic_tutorial#8]
The following instructions should have theoretically allowed the Visual Studio Code GUI to run within a docker on Windows. 

1. Follow the instructions in the FAQ Docker 'Setup VcXsrv X11 server on Windows' Section.

 Important:: Ensure you have followed step 4 of the VcXsrv setup instructions. This step saves the IP address of your computer as an environmental variable in a PowerShell terminal. This specific step is required to be repeated each time you run PyCharm via docker.

2. Run PyCharm in the docker:
    ```bash
    docker run `
        --rm `
        --env DISPLAY=${env:IPAddress}:0.0 `
        --name opencmiss-iron `
        -it `
        -v c/Users/${env:UserName}/Documents/oc/opt:/home/jovyan/work `
        -v c/Users/${env:UserName}/Documents/oc/usr/local:/home/jovyan/.local `
        -v c/Users/${env:UserName}/Documents/oc/usr/cache:/home/jovyan/.cache `
        -v c/Users/${env:UserName}/Documents/oc/usr/etc/jupyter:/etc/jupyter `
        -v c/Users/${env:UserName}/Documents/oc/usr/bin/:/usr/local/bin/ `
        -v c/Users/${env:UserName}/Documents/oc/usr/config:/home/jovyan/.config `
        -v c/Users/${env:UserName}/Documents/oc/usr/java:/home/jovyan/.java `
        prasadbabarendagamage/opencmiss-iron:1.0-minimal-ssh start-vs-code.sh
    ```

Important:: Ensure that there are no trailing spaces following the end-of-line tilda deliminators.

**Comment by PrasadBabarendaGamage** [comment]
However, this results in the following error.
[main 2021-01-27T10:38:47.405Z] Error: listen EIO: i/o error /home/jovyan/work/VSCode-linux-x64/data/user-data/1.52.1-main.sock
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1453:5)
    at /home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:217:373
    at new Promise (<anonymous>)
    at Object.t.serve (/home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:217:310)
    at Object.doStartup (/home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:654:11)
    at /home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:652:213
    at u.invokeFunction (/home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:295:578)
    at Object.startup (/home/jovyan/work/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:652:56)

**Comment by PrasadBabarendaGamage** [comment]
It is unclear how this issue can be addressed, so, for now, have stated that "This feature is not supported at this time."
